// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OLM.Services.TCO.API.Data;

namespace OLM.Services.TCO.API.Migrations
{
    [DbContext(typeof(TCODataDbContext))]
    partial class TCODataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OLM.Services.TCO.API.Models.TCODataModel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BundleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Primary")
                        .HasColumnType("float");

                    b.Property<string>("RawMaterialItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Secondary")
                        .HasColumnType("float");

                    b.Property<string>("VendorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Volume")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("TCOData");
                });

            modelBuilder.Entity("OLM.Services.TCO.API.Models.TCOValueSettingsModel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ExpectedTCOValue")
                        .HasColumnType("float");

                    b.Property<double>("MaximumDifference")
                        .HasColumnType("float");

                    b.Property<string>("RawMaterialItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TCOConstansValues");
                });
#pragma warning restore 612, 618
        }
    }
}
