version: '3.4'

services:

  web.gtw.spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - "bundles.api"
      - "identity.api"
      - "tco.api"
      - "categorybulbs.api"
      - "dailyreport.api"
      - "target.api"
      - "moneyexchangerate.api"
      - "routing.api"
      - "routing-data.api"
      - "routing-time.api"

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  bundles.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  tco.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"


  categorybulbs.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"


  dailyreport.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5005:80"

  target.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5006:80"

  moneyexchangerate.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5007:80"

  bundles-prices.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5009:80"

  tram.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:80"

  routing.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5011:80"

  routing-time.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5012:80"

  routing-data.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5013:80"

  tco.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  bundles.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  categorybulbs.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  bundles.prices.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  dailyreport.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro


  routingdata.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  routingtime.backgroundtasks.updater:
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

