// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OLM.Services.Bundles.API.Data;

namespace Bundles.API.Migrations
{
    [DbContext(typeof(BundlesDbContext))]
    [Migration("20210214155344_PrimaryAndSecondaryAdded")]
    partial class PrimaryAndSecondaryAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OLM.Services.Bundles.API.Models.BundleModel", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BundleID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FS")
                        .HasColumnType("float");

                    b.Property<DateTime>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Input")
                        .HasColumnType("float");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Primary")
                        .HasColumnType("float");

                    b.Property<double>("Produced")
                        .HasColumnType("float");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SawmillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Secondary")
                        .HasColumnType("float");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Waste")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Bundles");
                });
#pragma warning restore 612, 618
        }
    }
}
